services:
  ticketing:
    build:
      context: app
      dockerfile: Dockerfile
    ports:
      - 8000:8000
  postgres:
    image: postgres:16-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: "man_in_a_box"
      POSTGRES_USER: "gsb-ticketing"
      POSTGRES_DB: "gsb-data"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
