# Generated by Django 4.2.11 on 2024-03-05 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('checker', models.CharField(max_length=30)),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='scanner.ticket')),
            ],
        ),
    ]
