# Generated by Django 4.2.6 on 2023-10-24 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0003_namechange_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='is_ubus',
            field=models.BooleanField(default=False),
        ),
    ]
