# Generated by Django 4.2.6 on 2023-11-12 18:53

from django.db import migrations, models
import django.db.models.deletion
import ticketing.models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0004_ticket_is_ubus'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerApplicationRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enum', models.CharField(max_length=20, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('pay', models.DecimalField(decimal_places=2, default=12.9, max_digits=4)),
                ('description', models.CharField(max_length=600)),
            ],
            options={
                'db_table': 'workerapproles',
            },
        ),
        migrations.CreateModel(
            name='WorkerApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('cv', models.FileField(upload_to=ticketing.models.gen_workerapp_path)),
                ('uuid', models.CharField(default=ticketing.models.gen_workerapp_id, max_length=13)),
                ('cover_letter', models.FileField(upload_to=ticketing.models.gen_workerapp_path)),
                ('role', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='worker_applications', to='ticketing.workerapplicationrole')),
            ],
            options={
                'db_table': 'worker_applications',
            },
        ),
    ]
