# Generated by Django 4.2.6 on 2023-11-27 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0006_workerapplicationrole_workerapplication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workerapplication',
            name='cover_letter',
        ),
        migrations.RemoveField(
            model_name='workerapplication',
            name='cv',
        ),
        migrations.RemoveField(
            model_name='workerapplication',
            name='email',
        ),
        migrations.RemoveField(
            model_name='workerapplication',
            name='uuid',
        ),
        migrations.AddField(
            model_name='workerapplication',
            name='choice1',
            field=models.CharField(default='unselected', max_length=100),
        ),
        migrations.AddField(
            model_name='workerapplication',
            name='choice2',
            field=models.CharField(default='unselected', max_length=100),
        ),
        migrations.AddField(
            model_name='workerapplication',
            name='college',
            field=models.CharField(default='unselected', max_length=100),
        ),
        migrations.AddField(
            model_name='workerapplication',
            name='crsid',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='workerapplication',
            name='dob',
            field=models.DateField(default='2001-01-01'),
        ),
        migrations.AddField(
            model_name='workerapplication',
            name='exp_desc',
            field=models.TextField(default='', max_length=600),
        ),
        migrations.AddField(
            model_name='workerapplication',
            name='friends',
            field=models.CharField(default='', max_length=450),
        ),
        migrations.AddField(
            model_name='workerapplication',
            name='other_exp',
            field=models.TextField(default='', max_length=600),
        ),
        migrations.AddField(
            model_name='workerapplication',
            name='previous_exp',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workerapplication',
            name='qualities',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='workerapplication',
            name='reason',
            field=models.TextField(default='', max_length=400),
        ),
        migrations.AddField(
            model_name='workerapplication',
            name='supervisor',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='workerapplicationrole',
            name='description',
            field=models.TextField(max_length=600),
        ),
    ]
