# Generated by Django 4.2.6 on 2023-11-28 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0007_remove_workerapplication_cover_letter_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workerapplication',
            name='role',
        ),
        migrations.AlterField(
            model_name='workerapplication',
            name='choice1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='worker_app_choice_1', to='ticketing.workerapplicationrole'),
        ),
        migrations.AlterField(
            model_name='workerapplication',
            name='choice2',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='worker_app_choice_2', to='ticketing.workerapplicationrole'),
        ),
    ]
