# Generated by Django 4.2.6 on 2023-10-24 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0009_ticket_bus_destination_ticket_is_departure_bus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='is_departure_bus',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ticket',
            name='bus_destination',
            field=models.CharField(max_length=100),
        ),
    ]
