# Generated by Django 4.2.11 on 2024-11-12 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0010_ticket_is_departure_bus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='bus_destination',
            field=models.CharField(default='unselected', max_length=100),
        ),
    ]
