python3 manage.py loaddata payment_method.json
python3 manage.py loaddata ticket_extra.json
python3 manage.py loaddata ticket_allocation.json
python3 manage.py loaddata ticket_kind.json
python3 manage.py loaddata user_kind.json
python3 manage.py loaddata wave.json
python3 manage.py loaddata setting.json
python3 manage.py loaddata flat_page.json
python3 manage.py loaddata promocode.json
python3 manage.py loaddata allowed_user.json
